baseURL = "https://www.kaisawind.com/"
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
title = "kaisawind's blog"
theme = "hugo.386"
pygmentsCodeFences = true
pygmentsUseClasses = true
preserveTaxonomyNames = true
copyright = "©2016-2024 kaisawind"

[params]
  # The name to display as main title in the home page
  mainpagetitle = "Kaisawind Blog"
  # The subtitle to display under the title in the home page
  mainpagesubtitle = "https://github.com/kaisawind"
  # The description of your website. It will be displayed in the home page
  mainpagedesc = "Based developer and systems engineer. Golang, NodeJS, Rust, React, VUE, Docker, Linux, Arm, k8s @iotxfoundry"

  # The name to display in the copyright section in the footer
  copyrightname = "辽ICP备2021007608号©2016-2024 kaisawind"
  # The url to use as link in the copyright name in the footer. Leave empty to use none.
  copyrighturl = "https://beian.miit.gov.cn/"

  # Show the "built on Hugo" disclaimer
  showhugo = false

  # Urls for social networks
  github = "https://github.com/kaisawind"
  facebook = "https://facebook.com/kaisawind"
  twitter = "https://x.com/kaisawind"

  # Enables or disables the loading animations. false activates them. Default is false.
  loadfastload = false

  # Sets the speed for the page loading effect. Default is 1.0.
  loadspeedfactor = 1.0

  # Enables or disables the second flyby cursor. Default is false.
  loadonepass = false

[params.copyright]
    name = ""

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = "https://github.com/kaisawin"

    # Text to go before copyright information
    prefix = "[辽ICP备2021007608号](https://beian.miit.gov.cn/d)"

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = "kaisawind"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "关于"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "所有帖子"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

lastmod = true

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = "UA-133305125-1"
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true

[taxonomies]
category = "categories"
tag = 'tags'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]